In [3]:
import numpy as np
A = np.random.randint(0,5,(15,3))
print(A,"\n")
B = np.random.randint(0,5,(2,2))
print(B,"\n")
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[2 1 1]
 [0 0 2]
 [0 2 2]
 [4 2 4]
 [2 4 2]
 [3 4 0]
 [3 0 0]
 [3 2 2]
 [4 1 2]
 [1 1 1]
 [4 4 1]
 [3 0 3]
 [1 1 0]
 [2 1 2]
 [0 1 0]] 

[[2 2]
 [4 0]] 

[ 0  1  2  3  4  5  6  7  8 10 13 14]
